[package]
name = "risc0-circuit-rv32im-v2"
description = "RISC Zero circuit for rv32im-v2"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[[example]]
name = "rv32im_v2"
required-features = ["prove"]

[dependencies]
anyhow = { version = "1.0", default-features = false }
bytemuck = "1.13"
derive_more = { version = "1.0", default-features = false, features = [
  "add",
  "add_assign",
  "debug",
] }
paste = "1.0"
risc0-binfmt = { workspace = true }
risc0-core = { workspace = true }
risc0-zkp = { workspace = true, default-features = false }
serde = { version = "1.0", default-features = false, features = [
  "derive",
  "alloc",
] }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
auto_ops = { version = "0.3", optional = true }
byteorder = { version = "1.5", optional = true }
cfg-if = { version = "1.0", optional = true }
ibig = { version = "0.3.6", optional = true }
num-derive = { version = "0.4.2", optional = true }
num-traits = { version = "0.2.19", optional = true }
rand = { version = "0.8", optional = true }
rayon = { version = "1.5", optional = true }
ringbuffer = { version = "0.15.0", optional = true }
risc0-circuit-rv32im-v2-sys = { workspace = true, optional = true }
risc0-sys = { workspace = true, optional = true }

[dev-dependencies]
clap = { version = "4.5", features = ["derive"] }
flate2 = "1.0"
tar = "0.4"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
circuit_debug = ["risc0-zkp/circuit_debug"]
cuda = [
  "prove",
  "risc0-circuit-rv32im-v2-sys/cuda",
  "risc0-sys/cuda",
  "risc0-zkp/cuda",
]
default = ["prove"]
entropy_finder = []
execute = [
  "anyhow/backtrace",
  "dep:auto_ops",
  "dep:byteorder",
  "dep:ibig",
  "dep:num-derive",
  "dep:num-traits",
  "dep:ringbuffer",
  "risc0-core/perf",
  "std",
]
prove = [
  "dep:cfg-if",
  "dep:rand",
  "dep:rayon",
  "dep:risc0-circuit-rv32im-v2-sys",
  "dep:risc0-sys",
  "execute",
  "risc0-zkp/prove",
]
std = [
  "anyhow/std",
  "derive_more/std",
  "risc0-binfmt/std",
  "risc0-zkp/std",
  "serde/std",
]
