[package]
name = "risc0-circuit-recursion"
description = "RISC Zero circuit for recursion"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
exclude = ["src/recursion_zkr.zip"]

[dependencies]
anyhow = { version = "1.0", default-features = false }
cfg-if = { version = "1.0", optional = true }
risc0-core = { workspace = true }
risc0-zkp = { workspace = true }
serde = { version = "1.0", default-features = false, features = [
  "alloc",
  "derive",
], optional = true }
sha2 = { version = "0.10", optional = true }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }

[target.'cfg(any(target_os="macos", target_os="ios"))'.dependencies]
metal = { workspace = true }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
bytemuck = "1.12"
cust = { version = "0.3", optional = true }
lazy-regex = { version = "3.2", optional = true }
nvtx = { version = "1.3", optional = true }
rand = { version = "0.8", optional = true }
rayon = { version = "1.5", optional = true }
risc0-circuit-recursion-sys = { workspace = true, optional = true }
risc0-sys = { workspace = true, optional = true }
zip = { version = "2.1", default-features = false, optional = true, features = [
  "deflate",
] }

[dev-dependencies]
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tracing-forest = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
downloader = { version = "0.2", default-features = false, features = [
  "rustls-tls",
  "verify",
], optional = true }
hex = "0.4"
sha2 = { version = "0.10", optional = true }

[features]
cuda = [
  "dep:cust",
  "prove",
  "risc0-circuit-recursion-sys/cuda",
  "risc0-sys?/cuda",
  "risc0-zkp/cuda",
  "std",
]
default = ["prove", "test"]
prove = [
  "dep:cfg-if",
  "dep:downloader",
  "dep:lazy-regex",
  "dep:nvtx",
  "dep:rand",
  "dep:rayon",
  "dep:risc0-sys",
  "dep:serde",
  "dep:sha2",
  "dep:zip",
  "risc0-zkp/prove",
  "risc0-circuit-recursion-sys",
  "std",
]
std = ["risc0-zkp/std"]
test = []
