[package]
name = "risc0-zkvm-circuit-gen"
version = "0.11.0"
edition = "2021"
description = "RISC-V circuit (generated)"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"
links = "risc0-zkvm-circuit-gen"

[lib]
path = "lib.rs"

[build-dependencies]
risc0-zkvm-circuit-sys = { version = "0.11", path = ".." }
