[package]
name = "prorata-cli"
version = "0.1.0"
edition = { workspace = true }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
prove = ["risc0-zkvm/prove"]

[dependencies]
bincode = "1.3"
clap = { version = "4.3", features = ["derive"] }
prorata-core = { path = "core" }
prorata-methods = { path = "methods" }
risc0-zkvm = { path = "../../risc0/zkvm" }
rust_decimal = "1.29"

[dev-dependencies]
gpu-guard = { path = "../../tools/gpu-guard" }
