[package]
name = "prorata-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
ciborium = "0.2"
clap = { version = "4.3", features = ["derive"] }
prorata-core = { path = "core" }
prorata-methods = { path = "methods" }
risc0-zkvm = { path = "../../risc0/zkvm" }
rust_decimal = "1.29"
rust_decimal_macros = "1.29"
serde = "1.0"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
metal = ["risc0-zkvm/metal"]
