[package]
name = "smoke-test"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = "2.3.1"
# Use this only for testing locally before a release.
# risc0-zkvm = { path = "../../risc0/zkvm" }
methods = { path = "methods" }
