[package]
name = "risc0-zkp-verify"
version = "0.2.0"
edition = "2021"
description = "RISC Zero zero-knowledge proof system verify crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"
links = "risc0-zkp-verify"

[features]
default = ["pure"]
cxx = ["dep:cxx", "risc0-zkp-core/cxx"]
pure = ["dep:rand"]

[dependencies]
cfg-if = "1.0"
cxx = { version = "1.0", optional = true }
rand = { version = "0.8", default-features = false, features = ["small_rng"], optional = true }
risc0-zkp-core = { version = "0.2", path = "../core" }

[build-dependencies]
cxx-build = "1.0"
