[package]
name = "risc0-sys"
description = "Generated / Native / HAL code for RISC Zero"
version = "5.0.0-rc.1"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
links = "risc0-sys"

[features]
default = []
cuda = ["dep:blst", "dep:cust", "risc0-sppark/cuda"]
metal = []

[dependencies]
anyhow = { version = "1.0", default-features = false }
blst = { version = "~0.3.11", optional = true }
cust = { version = "0.3", optional = true }
risc0-sppark = { workspace = true, optional = true }

[build-dependencies]
risc0-build-kernel = { workspace = true }
