[package]
name = "p256-example"
version = "0.1.0"
edition = "2024"

default-run = "p256-example"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
prove = ["risc0-zkvm/prove"]

[dependencies]
p256 = { version = "0.13.2", features = ["serde"] }
p256-methods = { path = "methods" }
rand_core = "0.6.4"
risc0-zkvm = { path = "../../../risc0/zkvm" }
