[package]
name = "hotbench"
version = "0.1.0"
edition = { workspace = true }
publish = false

[package.metadata.release]
release = false

[dependencies]
cargo_metadata = "0.19.1"
human-repr = "1.0"
serde = "1.0"
serde_json = "1.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
