[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { path = "../../risc0/build" }

[package.metadata.risc0]
methods = ["chess", "digital-signature", "factors", "json", "sha"]
