[package]
name = "k256-example"
version = "0.1.0"
edition = "2021"

default-run = "k256-example"

[dependencies]
k256-methods = { path = "methods" }
k256 = { version = "0.13", features = ["serde"] }
rand_core = "0.6.4"
risc0-zkvm = { path = "../../../risc0/zkvm" }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
prove = ["risc0-zkvm/prove"]
