[package]
name = "risc0-js"
description = "Risc0 wasm on javascript bindings"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
bincode = "1.3"
risc0-zkvm = { workspace = true, default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.3"
risc0-zkvm-receipts = { path = "../../risc0/zkvm/receipts" }
