[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = { path = "../../../../risc0/build" }

[dependencies]
evm-core = { path = "../../core", default-features = false }
risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false, features = [ "std" ] }
externc-libm = { git = "https://github.com/HaruxOS/externc-libm" }
