[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
evm-core = { path = "../../core", default-features = false }
risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false, features = [ "std" ] }

[patch.crates-io]
radium = { git = 'https://github.com/ferrilab/radium.git' }
