[package]
name = "risc0-benchmark-methods-guest"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
blake3 = { version = "1.4", default-features = false }
ed25519-dalek = { version = "=2.1.1", default-features = false }
k256 = { version = "=0.13.4", features = [
  "arithmetic",
  "serde",
  "expose-field",
  "std",
  "ecdsa",
], default-features = false }
nalgebra = "0.32"
risc0-benchmark-lib = { path = "../../shared", default-features = false }
risc0-zkvm = { path = "../../../risc0/zkvm", default-features = false, features = [
  "std",
  "unstable"
] }
risc0-zkp = { path = "../../../risc0/zkp", default-features = false }
sha3 = { version = "0.10", default-features = false }
starknet-crypto = "0.6"

[patch.crates-io]
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
ed25519-dalek = { git = "https://github.com/risc0/curve25519-dalek", tag = "curve25519-4.1.3-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.4-risczero.1" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.9-risczero.0" }

[profile.release]
lto = true
