[package]
name = "risc0-zkos-common"
description = "RISC Zero zero-knowledge VM kernel common utilities"
version = "5.0.0-rc.1"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
risc0-zkvm-platform = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(rust_analyzer)'] }
