[package]
name = "risc0-r0vm"
version = "0.11.1"
edition = "2021"
description = "RISC Zero zero-knowledge VM executable"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
anyhow = "1.0"
bytemuck = "1.12"
clap = { version = "3.2", features = ["derive"] }
env_logger = "0.9.0"
risc0-zkvm = { version = "0.11", path = "../sdk/rust" }

[dev-dependencies]
anyhow = "1.0"
assert_cmd = "2.0"
assert_fs = "1.0"
risc0-zkvm-methods = { path = "../sdk/rust/methods" }

[features]
pure-prove = ["risc0-zkvm/pure-prove"]

