[package]
name = "voting-machine"
version = "0.12.0"
edition = "2021"

[dependencies]
risc0-zkvm = { path = "../../risc0/zkvm" }
voting-machine-core = { path = "core" }
voting-machine-methods = { path = "methods" }
tracing = { version = "0.1", features = ["log"] }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
hex = "0.4"
test-log = { version = "0.2", default-features = false, features = ["trace"] }

[features]
default = []
cuda = ["risc0-zkvm/cuda"]
prove = ["risc0-zkvm/prove"]
profiler = ["risc0-zkvm/profiler"]
