[package]
name = "risc0-zkvm-host"
version = "0.7.1"
edition = "2021"
description = "RISC Zero zero-knowledge VM host crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
ctor = "0.1"
cxx = "1.0"
log = "0.4"
risc0-zkvm-sys = { version = "0.7", path = "../../.." }

[build-dependencies]
cxx-build = "1.0"

[dev-dependencies]
anyhow = "1.0"
risc0-zkvm-core = { path = "../core" }
risc0-zkvm-methods = { path = "../methods" }
risc0-zkvm-serde = { path = "../serde" }
tempfile = "3.3"
