[package]
name = "risc0-zkvm-circuit"
version = "0.11.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM circuit"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
anyhow = "1.0"
log = "0.4"
risc0-zkp = { version = "0.11", path = "../../../../zkp/rust" }

[dev-dependencies]
env_logger = "0.9"

# This is required to prevent a stack overflow in rustc
[profile.dev]
debug = false
