[package]
name = "xtask"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
bincode = "1.3"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
regex = "1"
risc0-circuit-recursion = { workspace = true, features = ["prove"] }
risc0-core = { workspace = true }
risc0-groth16 = { workspace = true, features = ["prove"] }
risc0-zkp = { workspace = true }
risc0-zkvm = { workspace = true, features = ["prove"] }
risc0-zkvm-methods = { path = "../risc0/zkvm/methods" }
risc0-zkvm-methods-core = { workspace = true }
tempfile = "3.3"
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
which = "6.0"
xshell = "0.2"

[package.metadata.release]
release = false
