[package]
name = "xtask"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
bincode = "1.3"
clap = { version = "4", features = ["derive"] }
log = "0.4"
regex = "1"
risc0-core = { workspace = true }
risc0-zkp = { workspace = true }
risc0-zkvm = { workspace = true, features = ["default"] }
risc0-zkvm-methods = { path = "../risc0/zkvm/methods" }
tempfile = "3.5"
which = "4.4"
xshell = "0.2"

[package.metadata.release]
release = false
