[package]
name = "xgboost-example"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
forust-ml = "0.4.2"
risc0-zkvm = { path = "../../risc0/zkvm" }
rmp-serde = "1.1.2"
serde_json = "1.0.108"
xgboost-methods = { path = "methods" }

[dev-dependencies]
gpu-guard = { path = "../../tools/gpu-guard" }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
prove = ["risc0-zkvm/prove"]
