[package]
name = "risc0-groth16-sys"
description = "C++ code for groth16 proof generation"
version = "0.2.0"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
links = "risc0-groth16-sys"

[build-dependencies]
risc0-build-kernel = { workspace = true }

[dependencies]
anyhow = "1.0.98"
blst = { version = "0.3.15", optional = true }
risc0-sppark = { workspace = true, optional = true }

[dev-dependencies]
test-log = { version = "0.2.17", default-features = false, features = [
  "trace",
] }
tracing = "0.1.41"

[features]
default = []
cuda = ["dep:blst", "risc0-sppark/cuda"]
metal = []
# Build code used for preprocessing of prover parameters.
# Used in the xtask setup-groth16 command for the development of this crate.
setup = []
