[package]
name = "c-kzg-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
c-kzg = { git = "https://github.com/risc0/c-kzg-4844.git", rev = "304eacb4f5fec09e837936e4ada6705ecac581f0", default-features = false, features = [
    "std"
] }
util = { path = "../../util" }

[package.metadata.risc0]
methods = ["guest"]

[features]
prove = ["util/prove"]
