[workspace]
resolver = "2"

[package]
name = "risc0-zkvm-methods-cfg"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { path = "../..", default-features = false }

[profile.release]
lto = true
opt-level = 3
debug = 1

[package.metadata.risc0]
rustc-flags = ['--cfg', 'risc0_custom_cfg_test="flagged"']

[package.metadata.release]
release = false
