[package]
name = "risc0-circuit-bigint-test-methods"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
num-bigint = { version = "0.4", default-features = false, features = ["serde"] }
risc0-circuit-bigint = { path = "../..", default-features = false }
risc0-zkvm = { path = "../../../../zkvm", default-features = false, features = [
    "std",
    "unstable",
] }
