[package]
name = "risc0-bigint2-methods"
version = { workspace = true }
edition = { workspace = true }

[package.metadata.release]
release = false

[package.metadata.risc0]
methods = ["guest"]

[features]
num-bigint-dig = []

[build-dependencies]
risc0-build = { workspace = true }
