[package]
name = "risc0-povw"
description = "Core library for RISC Zero Proof of Verifiable Work (PoVW)"
version = "0.5.0"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[features]
default = ["guest", "prover"]
prover = ["guest", "risc0-zkvm/client", "dep:derive_builder", "dep:anyhow"]
guest = ["dep:derive_builder"]

[dependencies]
anyhow = { version = "1.0", optional = true }
borsh = { version = "1.5", default-features = false, features = [
    "derive",
    "std",
] }
bytemuck = "1.22"
derive_builder = { version = "0.20.2", optional = true }
hybrid-array = { version = "0.3.0", features = ["serde"] }
risc0-binfmt = { workspace = true }
risc0-zkvm = { workspace = true }
ruint = { version = "1.15", features = ["serde"] }
serde = "1"
thiserror = "1.0"

[dev-dependencies]
proptest = "1.6.0"
ruint = { version = "1.15", features = ["proptest"] }
