[package]
name = "risc0-zkvm-serde"
version = "0.2.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM serde crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
bytemuck = { version = "1.9" }
serde = { version = "1.0", default-features = false }

[features]
default = ["std"]
std = []
