[package]
name = "waldo"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.10"
image = "0.24"
risc0-zkvm = { path = "../../risc0/zkvm" }
serde = "1.0"
viuer = "0.6"
waldo-core = { path = "core" }
waldo-methods = { path = "methods" }

[features]
default = []
cuda = ["risc0-zkvm/cuda"]
prove = ["risc0-zkvm/cuda"]
profiler = ["risc0-zkvm/profiler"]
