[package]
name = "risc0-emu"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow = { version = "1.0", default-features = false }
bytemuck = "1.24.0"
derive_more = { version = "2.0.1", default-features = false, features = [
  "add",
  "add_assign",
  "debug",
] }
dynasmrt = "4.0.1"
iced-x86 = "1.21.0"
libc = "0.2.177"
risc0-binfmt = { workspace = true }
risc0-circuit-rv32im-m3-sys = { workspace = true }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }

[dev-dependencies]
rstest = "0.26.1"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
zip = { version = "6.0.0", default-features = false, features = ["deflate"] }

[build-dependencies]
cc = "1.2.47"

[lints]
workspace = true

[features]
block_tracker_debug = []
