[package]
name = "risc0-emu"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow = { version = "1.0", default-features = false }
derive_more = { version = "2.0.1", default-features = false, features = [
  "add",
  "add_assign",
  "debug",
] }
risc0-binfmt = { workspace = true }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }

[lints]
workspace = true
