[package]
name = "risc0-emu"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow = { version = "1.0", default-features = false }
bytemuck = "1.24.0"
derive_more = { version = "2.0.1", default-features = false, features = [
  "add",
  "add_assign",
  "debug",
] }
dynasmrt = "4.0.1"
iced-x86 = "1.21.0"
risc0-binfmt = { workspace = true }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }

[dev-dependencies]
test-log = { version = "0.2", default-features = false, features = ["trace"] }

[lints]
workspace = true
