[package]
name = "risc0-tools"
version = { workspace = true }
edition = { workspace = true }
description = "RISC Zero devtools"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
risc0-zkvm = { version = "0.12", path = "../zkvm", features = ["profiler"] }
