[package]
name = "risc0-tools"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "RISC Zero devtools"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
risc0-binfmt = { workspace = true }

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.12"
risc0-zkos-v1compat = { workspace = true }
