[package]
name = "risc0-zkvm-core"
version = "0.7.0-rc.1"
edition = "2021"
description = "RISC Zero zero-knowledge VM core crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
cfg-if = "1.0"
risc0-zkp-core = { version = "0.7.0-dev.1", path = "../../../../zkp/rust/core", default-features = false, optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = []

# The pure feature enables the 'pure' rust implementation of this crate.
pure = ["dep:risc0-zkp-core"]
