[package]
name = "validator"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
jwt-core = { path = "../../core/" }
# risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false, features = ["std"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", default-features = false, features = ["std"] }

[patch.crates-io]
# TODO: Make a permanent `rsa` patch
rsa = { path = "/Users/tzerrell/code/RustCrypto/RSA" }        # Base: * | a801f53 (tag: v0.9.6) v0.9.6 (#397)
