[package]
name = "methods"
version = "0.1.0"
edition = "2024"

[build-dependencies]
risc0-build = "1.0.5"
# Use this only for testing locally before a release.
# risc0-build = { path = "../../../risc0/build" }

[package.metadata.risc0]
methods = ["guest"]
