[package]
name = "risc0-circuit-bigint"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytemuck = "1.16.1"
clap = { version = "4.1", features = ["derive"], optional = true }
hex = "0.4"
log = "0.4"
num-bigint = { version = "0.4", default-features = false }
num-integer = "0.1"
num-traits = "0.2"
paste = "1.0"
pretty_assertions = "1.4"
risc0-binfmt = { workspace = true }
risc0-circuit-recursion = { workspace = true, default-features = false }
risc0-core = { workspace = true }
risc0-zkp = { workspace = true, features = ["default"] }
risc0-zkvm = { workspace = true, features = ["std", "unstable"], default-features = false }
risc0-zkvm-platform = { workspace = true }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"], optional = true }
zip = { version = "2.0", default-features = false, features = [
  "deflate",
] }

[dev-dependencies]
env_logger = "0.10"
num-bigint = { version = "0.4", default-features = false, features = ["serde"] }
test-log = { version = "0.2", features = ["trace"] }

[target.'cfg(not(target_os = "zkvm"))'.dev-dependencies]
risc0-circuit-bigint-test-methods = { path = "methods" }

[[bin]]
name = "make_control_ids"
required-features = ["make_control_ids"]

[features]
default = ["prove"]
# Enables ZKR registration to actually generate proofs.
prove = ["risc0-zkvm/prove", "risc0-circuit-recursion/prove"]
make_control_ids = ["dep:clap", "dep:tracing-subscriber"]
