[package]
name = "risc0-povw-log-builder"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[workspace]

[dependencies]
anyhow = "1"
borsh = { version = "1.5", default-features = false, features = ["std"] }
risc0-povw = { path = "../../", default-features = false }
risc0-zkvm = { path = "../../../zkvm/", default-features = false, features = ["std", "unstable"] }
ruint = { version = "1.15" }
