[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", branch = "release-0.16", features = ["guest-list"] }

[dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", branch = "release-0.16", features = ["guest-list"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "release-0.16" }

[dev-dependencies]
hex-literal = "0.4.1"
