[package]
name = "zkevm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers-core = { version = "2.0", optional = true }
ethers-providers = { version = "2.0", optional = true }
primitive-types = { version = "0.12", features = ["serde"] }
revm = { version = "3.5", default-features = false, features = [
  "std",
  "serde",
] }
serde = "1.0"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
], optional = true }

[features]
default = ["ethers"]
ethers = ["tokio", "ethers-providers", "ethers-core"]
