[package]
name = "password-checker"
version = "0.12.0"
edition = "2021"

[dependencies]
password-checker-core = { path = "core" }
password-checker-methods = { path = "methods" }
rand = "0.8"
risc0-zkvm = { path = "../../risc0/zkvm" }

[features]
cuda = ["risc0-zkvm/cuda", "password-checker-methods/prove"]
default = []
prove = ["risc0-zkvm/prove", "password-checker-methods/prove"]
