[package]
name = "digital-signature"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.1"
digital-signature-core = { path = "core" }
env_logger = "0.9"
log = "0.4"
methods = { path = "../methods" }
risc0-zkp = { path = "../../risc0/zkp" }
risc0-zkvm = { path = "../../risc0/zkvm" }
serde = "1.0"
sha2 = "0.10"

[dev-dependencies]
ctor = "0.1"

[features]
cuda = ["risc0-zkp/cuda", "risc0-zkvm/cuda"]
metal = ["risc0-zkp/metal", "risc0-zkvm/metal"]
