[workspace]
members = [
    "chess",
    "digital-signature",
    "factors",
    "json",
    "password-checker",
    "sha",
    "waldo",
    "wordle",
]

# Always optimize; otherwise tests take excessively long.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
