[workspace]
members = [
    "chess",
    "chess/core",
    "digital-signature",
    "digital-signature/core",
    "ecdsa",
    "evm",
    "evm/core",
    "factors",
    "json",
    "json/core",
    "password-checker",
    "password-checker/core",
    "prorata/host",
    "sha",
    "waldo",
    "waldo/core",
    "wasm",
    "wordle",
    "wordle/core",
]

# Always optimize; otherwise tests take excessively long.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
