[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "3.0.4", default-features = false }
# Use this only for testing locally before a release.
# risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false }
