[package]
name = "risc0-zkp-sys"
version = "0.1.0"
edition = "2021"
description = "RISC Zero zero-knowledge proof system crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"
links = "risc0-zkp-sys"

[lib]
path = "lib.rs"

[dependencies]
cxx = "1.0"
risc0-core-sys = { version = "0.7.0-dev.1", path = "../core" }
tbb = { version = "0.1", path = "../../third_party/tbb" }

[build-dependencies]
cxx-build = "1.0"
