[package]
name = "risc0-zkp-core"
version = "0.9.0"
edition = "2021"
description = "RISC Zero zero-knowledge proof system core crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[[bench]]
name = "ntt"
harness = false

[dependencies]
anyhow = { version = "1.0", default-features = false }
bytemuck = { version = "1.9", features = ["derive"] }
paste = "1.0"
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
rand_core = "0.6"
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = { version = "0.10", default-features = false, features = ["compress"] }

[dev-dependencies]
criterion = "0.3"
rand = { version = "0.8", features = ["small_rng"] }
