[package]
name = "profiling"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
env_logger = "0.10"
fibonacci-methods = { path = "methods" }
risc0-zkvm = { path = "../../risc0/zkvm", features = ["profiler"] }
serde = "1.0"

[features]
default = []
cuda = ["risc0-zkvm/cuda"]
prove = ["risc0-zkvm/cuda"]
profiler = ["risc0-zkvm/profiler"]
