[package]
name = "risc0-zkos-v1compat"
version = "2.0.0-rc.1"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[[bin]]
name = "v1compat"
path = "src/main.rs"

[dependencies]
include_bytes_aligned = "0.1"
no_std_strings = "0.1.3"

[package.metadata.release]
release = false

[package.metadata.risc0]
kernel = true
