[package]
name = "risc0-zkos-v1compat"
description = "RISC Zero zero-knowledge VM kernel for v1 compatibility"
version = "2.0.2-rc.3"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[[bin]]
name = "v1compat"
path = "src/main.rs"

[dependencies]
include_bytes_aligned = "0.1"
no_std_strings = "0.1.3"

[package.metadata.risc0]
kernel = true
