[package]
name = "risc0-zkos-v1compat"
description = "RISC Zero zero-knowledge VM kernel for v1 compatibility"
version = "2.2.2"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[package.metadata.risc0]
kernel = true

[[bin]]
name = "v1compat"
path = "src/main.rs"

[dependencies]
include_bytes_aligned = "0.1"
no_std_strings = "0.1.3"
risc0-zkos-common = { workspace = true }
risc0-zkvm-platform = { workspace = true }
sha2 = { version = "0.10.9", default-features = false, features = ["compress"] }

[dev-dependencies]
anyhow = "1.0"
flate2 = "1.0"
risc0-binfmt = { workspace = true }
risc0-zkvm = { workspace = true, features = ["prove", "client"] }
tar = "0.4"
test-log = { version = "0.2", default-features = false, features = ["trace"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(rust_analyzer)'] }
