[package]
name = "json-example"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
json-core = { path = "core" }
json-methods = { path = "methods" }
risc0-zkvm = { path = "../../risc0/zkvm" }

[dev-dependencies]
gpu-guard = { path = "../../tools/gpu-guard" }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
prove = ["risc0-zkvm/prove"]
