[package]
name = "risc0-zkp"
version = "0.11.1"
edition = "2021"
description = "RISC Zero zero-knowledge proof system core crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[[bench]]
name = "ntt"
harness = false

[dependencies]
anyhow = { version = "1.0", default-features = false }
array-init = { version = "2.0", optional = true }
bytemuck = { version = "1.12", features = ["derive"] }
log = { version = "0.4", optional = true }
ndarray = { version = "0.15", optional = true, features = ["rayon"] }
paste = "1.0"
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
rand_core = { version = "0.6", default-features = false }
rayon = { version = "1.5", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = { version = "0.10", optional = true, default-features = false, features = ["compress"] }

[dev-dependencies]
criterion = "0.3"
rand = { version = "0.8", features = ["small_rng"] }

[features]
default = ["host", "prove", "std", "verify"]
hal = ["dep:ndarray", "dep:rayon"]
host = ["dep:log"]
prove = ["dep:array-init", "dep:log", "dep:sha2", "hal", "rand/std", "rand/std_rng"]
std = []
verify = []
