[package]
name = "risc0-zkp"
version = "0.10.0"
edition = "2021"
description = "RISC Zero zero-knowledge proof system core crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[[bench]]
name = "ntt"
harness = false

[dependencies]
anyhow = { version = "1.0", default-features = false }
array-init = { version = "2.0", optional = true }
bytemuck = { version = "1.9", features = ["derive"] }
downcast-rs = { version = "1.2", optional = true }
log = "0.4"
paste = "1.0"
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
rand_core = "0.6"
rayon = { version = "1.5", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = { version = "0.10", default-features = false, features = ["compress"] }

[dev-dependencies]
criterion = "0.3"
rand = { version = "0.8", features = ["small_rng"] }

[features]
default = ["prove", "std", "verify"]
hal = ["dep:downcast-rs", "dep:rayon"]
prove = ["dep:array-init", "hal"]
std = []
verify = []
