[workspace]

[package]
name = "risc0-zkvm-methods-verify"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.11"
risc0-zkp = { version = "0.11", path = "../../../../../zkp/rust", default-features = false }
risc0-zkvm = { version = "0.11", path = "../..", default-features = false, features = ["pure-prove", "verify"] }
risc0-zkvm-circuit = { version = "0.11", path = "../../circuit", default-features = false }
risc0-zkvm-guest = { version = "0.11", path = "../../guest", default-features = false, features = ["pure-prove"] }
risc0-zkvm-platform = { version = "0.11", path = "../../platform", features = ["pure-prove"] }

[profile.release]
lto = true
opt-level = 3

[build-dependencies]
risc0-build = { version = "0.11", path = "../../build", features = ["pure-prove"] }

[package.metadata.release]
release = false

[features]
pure-prove = []
