[package]
name = "battleship-web-client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
battleship-core = { path = "../../core" }
getrandom = { version = "0.2", features = ["js"] }
gloo = { version = "0.7", features = ["futures"] }
js-sys = "0.3"
log = "0.4"
# near-sdk = "3.1"
rand = { version = "0.8", features = ["small_rng"] }
reqwasm = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.4"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
weblog = "0.3"
web-sys = { version = "0.3", features = ["HtmlInputElement"] }
yew = "0.19"
yew-agent = "0.1"
yew-router = "0.16"
