[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { path = "../../risc0/zkvm" }
serde = "1.0"
wasm-methods = { path = "methods" }
wat = "<1.0.72"

[features]
default = []
cuda = ["risc0-zkvm/cuda"]
prove = ["risc0-zkvm/cuda"]
profiler = ["risc0-zkvm/profiler"]
