[package]
name = "risc0-zkvm-guest"
version = "0.11.0-rc.2"
edition = "2021"
description = "RISC Zero zero-knowledge VM guest crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
bytemuck = "1.9"
risc0-zkp = { version = "0.11.0-rc.2", path = "../../../../zkp/rust", default-features = false }
risc0-zkvm = { version = "0.11.0-rc.2", path = "..", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[build-dependencies]
risc0-build = { version = "0.11.0-rc.2", path = "../build" }

[features]
bazel = []
default = ["std"]
doc = ["std"]
std = ["risc0-zkp/std", "serde/std"]

[package.metadata.release]
release = false

[workspace]
