[package]
name = "risc0-circuit-rv32im-sys"
description = "Generated HAL code for rv32im circuit"
version = "4.0.2"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
links = "risc0-circuit-rv32im-sys"

[dependencies]
cust = { version = "0.3", optional = true }
derive_more = { version = "2.0.1", features = ["debug"] }
risc0-core = { workspace = true }
risc0-sppark = { workspace = true, optional = true }
risc0-sys = { workspace = true }

[build-dependencies]
cc = { version = "1.2.2", features = ["parallel"] }
glob = "0.3"
risc0-build-kernel = { workspace = true }

[features]
default = []
cuda = ["dep:cust", "risc0-sppark/cuda", "risc0-sys/cuda"]
metal = []
