[package]
name = "risc0-circuit-rv32im-sys"
description = "Generated HAL code for rv32im circuit"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
links = "risc0-circuit-rv32im-sys"

[features]
prove = ["dep:risc0-sys", "dep:risc0-zkp"]
cuda = ["prove", "risc0-sppark/cuda", "risc0-sys/cuda"]
default = []

[dependencies]
anyhow = { version = "1.0", default-features = false }
bytemuck = { version = "1.13", features = ["min_const_generics"] }
derive_more = { version = "2.0.1", default-features = false, features = ["from"] }
enum-map = "2.7.3"
risc0-sppark = { workspace = true, optional = true }
risc0-sys = { workspace = true, optional = true }
risc0-zkp = { workspace = true, default-features = false, optional = true }
serde = { version = "1.0", default-features = false, features = [
  "derive",
  "alloc",
] }
strum = { version = "0.27.1", features = ["derive"] }
tracing = { version = "0.1", default-features = false, features = [
    "attributes",
] }

[build-dependencies]
anyhow = { version = "1.0", default-features = false }
bindgen = "0.72"
cc = { version = "1.2.2", features = ["parallel"] }
glob = "0.3"
quote = "1"
regex = "1"
risc0-build-kernel = { workspace = true }
xshell = "0.2"
