[package]
name = "risc0-zkvm-compat-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
risc0-r0vm = { workspace = true }
risc0-zkp = { workspace = true }
risc0-zkvm = { workspace = true, features = ["client", "r0vm-ver-compat"] }
risc0-zkvm-methods = { path = "../methods", features = ["std"] }
semver = "1.0.25"

[dev-dependencies]
rstest = "0.24.0"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
