[package]
name = "risc0-build-kernel"
description = "RISC Zero tool for building kernels"
version = "2.0.1"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
cc = { version = "1.2.20", features = ["parallel"] }
directories = "6.0.0"
hex = "0.4"
rayon = "1.10"
sha2 = "0.10"
tempfile = "3.12"
