[package]
name = "risc0-circuit-keccak-methods"
version = "0.1.0"
edition = "2024"

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.release]
release = false

[package.metadata.risc0]
methods = ["guest"]
