[package]
name = "risc0-circuit-rv32im"
version = "0.12.0"
edition = "2021"
description = "RISC Zero circuit for rv32im"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"
exclude = ["/*.cpp", "/*.h", "/test", "BUILD.bazel", "*.inl"]

[[bench]]
name = "eval_check"
harness = false

[dependencies]
anyhow = { version = "1.0", default-features = false }
risc0-zkp = { path = "../../../risc0/zkp", default-features = false }
risc0-zkvm-platform = { version = "0.12", path = "../../../risc0/zkvm/platform" }
tracing = { version = "0.1", default-features = false, features = ["attributes"] }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
fil-rustacuda = { version = "0.1", optional = true }
log = "0.4"
rand = "0.8"
rayon = "1.5"
rustacuda_core = { version = "0.1", optional = true }
rustacuda_derive = { version = "0.1", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.24"

[dev-dependencies]
criterion = "0.4"
env_logger = "0.10"
test-log = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
glob = "0.3"
sha2 = "0.10"

[features]
cuda = ["dep:fil-rustacuda", "dep:rustacuda_core", "dep:rustacuda_derive", "risc0-zkp/cuda", "std"]
default = ["std", "test"]
std = []
test = []
verify-only = []
