[package]
name = "risc0-circuit-rv32im"
description = "RISC Zero circuit for rv32im"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { version = "1.0", default-features = false }
risc0-binfmt = { workspace = true }
risc0-core = { workspace = true }
risc0-zkp = { workspace = true }
risc0-zkvm-platform = { workspace = true }
serde = { version = "1.0", default-features = false, features = [
  "derive",
  "alloc",
] }
smallvec = { version = "1.13", optional = true }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }

[target.'cfg(any(target_os="macos", target_os="ios"))'.dependencies]
metal = { workspace = true }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
auto_ops = { version = "0.3", optional = true }
bytemuck = { version = "1.13", optional = true }
byteorder = { version = "1.5", optional = true }
cfg-if = { version = "1.0", optional = true }
crossbeam = { version = "0.8", optional = true }
crypto-bigint = { version = "0.5", default-features = false, optional = true }
cust = { version = "0.3", optional = true }
derive_more = { version = "2.0.1", features = ["debug"], optional = true }
enum-map = { version = "2.7.3", optional = true }
lazy-regex = { version = "3.3", optional = true }
malachite = { version = "0.5", optional = true, default-features = false, features = [
  "naturals_and_integers",
  "32_bit_limbs",
] }
num-derive = { version = "0.4", optional = true }
num-traits = { version = "0.2", optional = true }
rand = { version = "0.8", optional = true }
rayon = { version = "1.5", optional = true }
risc0-circuit-rv32im-sys = { workspace = true, optional = true }
risc0-sys = { workspace = true, optional = true }
sha2 = { version = "0.10", default-features = false, optional = true }

[dev-dependencies]
test-log = { version = "0.2", default-features = false, features = ["trace"] }

[features]
cuda = [
  "dep:cust",
  "prove",
  "risc0-circuit-rv32im-sys?/cuda",
  "risc0-sys?/cuda",
  "risc0-zkp/cuda",
  "std",
]
default = ["prove"]
metal = ["prove"]
prove = [
  "dep:auto_ops",
  "dep:bytemuck",
  "dep:byteorder",
  "dep:cfg-if",
  "dep:crossbeam",
  "dep:crypto-bigint",
  "dep:derive_more",
  "dep:enum-map",
  "dep:lazy-regex",
  "dep:malachite",
  "dep:num-derive",
  "dep:num-traits",
  "dep:rand",
  "dep:rayon",
  "dep:risc0-circuit-rv32im-sys",
  "dep:risc0-sys",
  "dep:sha2",
  "dep:smallvec",
  "risc0-core/perf",
  "risc0-zkp/prove",
  "std",
]
std = ["risc0-zkp/std", "serde/std"]
