[package]
name = "risc0-zirgen-dsl"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }


[dependencies]
anyhow = "1.0"
bytemuck = "1.14"
clap = { version = "4.1", features = ["derive"] }
env_logger = "0.11"
lazy_static = "1.4"
paste = "1.0"
pretty_assertions = "1.4"
rayon = "1.8"
risc0-core = { workspace = true }
risc0-zkp = { workspace = true, default-features = false, features = ["prove"] }
serial_test = "3.1"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
test-log = { version = "0.2", features = ["trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[[example]]
name = "calculator"
test = true
