[package]
name = "risc0-make-id"
version = "0.11.0"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
risc0-zkvm = { version = "0.11", path = "../../sdk/rust" }

[package.metadata.release]
release = false
