name: Release

on:
  push:
    tags:
      - "v*.*.*"
  # for testing purposes
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          tag_name: test-release-1 # only for testing

  build-linux:
    runs-on: [self-hosted, prod, Linux, docker, cpu]
    needs: release
    container:
      image: nvidia/cuda:12.2.2-devel-ubi8
    env:
      OS: Linux
      FEATURE: cuda
      RUSTC_WRAPPER: sccache
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: ${{ env.OS }}-${{ env.FEATURE }}
      - run: cargo build -p cargo-risczero --release
      - run: |
          mkdir -p tmp/pkg
          cp target/release/cargo-risczero tmp/pkg
          cp target/release/r0vm tmp/pkg
      - run: cargo build -p cargo-risczero --release -F $FEATURE
      - run: |
          cp target/release/r0vm tmp/pkg/r0vm-$FEATURE
          cd tmp/pkg && tar cv * | gzip -9 > ../cargo-risczero-$TARGET.tgz
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/cargo-risczero-${{ env.TARGET }}.tgz
          tag: test-release-1 # only for testing

  build-macos:
    runs-on: [self-hosted, prod, macOS, apple_m2_pro]
    needs: release
    env:
      OS: macOS
      FEATURE: metal
      RUSTC_WRAPPER: sccache
      TARGET: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: ${{ env.OS }}-${{ env.FEATURE }}
      - run: cargo build -p cargo-risczero --release
      - run: |
          mkdir -p tmp/pkg
          cp target/release/cargo-risczero tmp/pkg
          cp target/release/r0vm tmp/pkg
      - run: cargo build -p cargo-risczero --release -F $FEATURE
      - run: |
          cp target/release/r0vm tmp/pkg/r0vm-$FEATURE
          cd tmp/pkg && tar cv * | gzip -9 > ../cargo-risczero-$TARGET.tgz
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/cargo-risczero-${{ env.TARGET }}.tgz
          tag: test-release-1 # only for testing
