name: Release

on:
  push:
    tags:
      - "v*.*.*"
  # for testing purposes
  # pull_request:
  #   branches: [main, "release-*"]

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: write

env:
  RISC0_TOOLCHAIN_VERSION: r0.1.79.0
  TAG: v1.0.0
  VERSION: "1.0.0"

jobs:
  release:
    runs-on: [self-hosted, prod, "${{ matrix.os }}", cpu]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: Linux
            target: x86_64-unknown-linux-gnu
          - os: macOS
            target: aarch64-apple-darwin
    env:
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: git lfs pull
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: ${{ env.TARGET }}
      - if: matrix.os == 'Linux'
        run: docker build -f .github/containers/release/Dockerfile --output tmp/pkg .
      - if: matrix.os == 'macOS'
        run: |
          cargo build -p cargo-risczero --release
          mkdir -p tmp/pkg
          cp target/release/cargo-risczero tmp/pkg
          cp target/release/r0vm tmp/pkg
      - run: tar cv * | gzip -9 > ../cargo-risczero-$TARGET.tgz
        working-directory: tmp/pkg
      - uses: svenstaro/upload-release-action@v2
        with:
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/cargo-risczero-${{ env.TARGET }}.tgz
          # tag: ${{ env.TAG }} # only for testing

      # wait for recently uploaded release asset to become available,
      # otherwise cargo-binstall sometimes errors with 404.
      - run: sleep 90

      - uses: risc0/cargo-install@9f6037ed331dcf7da101461a20656273fa72abf0
        with:
          crate: cargo-binstall
          version: "1.4"
      - run: cargo binstall -y --force cargo-risczero@${{ env.VERSION }}
      - run: cargo risczero install --version $RISC0_TOOLCHAIN_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo run
        working-directory: tools/smoke-test
