name: website

on:
  merge_group:
  pull_request:
    branches: [main, "release-*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # see: https://github.com/orgs/community/discussions/26822
  website-status-check:
    if: always()
    needs:
      - check
      - doc-test-main
      - doc-test-stable
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
        # see https://stackoverflow.com/a/67532120/4907315
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1

  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      check: ${{ steps.filter.outputs.check }}
      doc-test-main: ${{ steps.filter.outputs.doc-test-main }}
      doc-test-stable: ${{ steps.filter.outputs.doc-test-stable }}
    steps:
      - uses: actions/checkout@v4
      - uses: risc0/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            check:
              - .github/workflows/website.yml
              - website/**
            doc-test-main:
              - rust-toolchain.toml
              - .github/actions/**
              - .github/workflows/website.yml
              - bonsai/**
              - risc0/**
              - website/api/**
              - website/doc-test/main/**
              - website/docs/**
            doc-test-stable:
              - .github/actions/**
              - .github/workflows/website.yml
              - website/api_versioned_docs/version-0.21/**
              - website/doc-test/stable/**

  check:
    if: needs.changes.outputs.check == 'true'
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: npx prettier website --check
      - run: python website/link-version-check.py

  doc-test-main:
    if: needs.changes.outputs.doc-test-main == 'true'
    needs: changes
    runs-on: [self-hosted, prod, Linux, cpu]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: Linux-default
      - run: cargo run --bin rzup -- --verbose install rust $RISC0_RUST_TOOLCHAIN_VERSION
      - run: cargo run --bin rzup -- --verbose install cpp $RISC0_CPP_TOOLCHAIN_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RISC0_RUST_TOOLCHAIN_VERSION: r0.1.79.0
          RISC0_CPP_TOOLCHAIN_VERSION: 2024.01.05

      - name: build
        run: cargo test --release --no-run
        working-directory: website/doc-test/main
      - name: test
        run: cargo test --release
        working-directory: website/doc-test/main

      - run: sccache --show-stats

  doc-test-stable:
    if: needs.changes.outputs.doc-test-stable == 'true'
    needs: changes
    runs-on: [self-hosted, prod, Linux, cpu]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: Linux-default
      - uses: risc0/cargo-install@9f6037ed331dcf7da101461a20656273fa72abf0
        with:
          crate: cargo-binstall
          version: "1.4"
      - run: cargo binstall -y --force cargo-risczero@1.0
      # note: this uses an older version of risc0-build in the release-1.0 branch
      # Leave the old toolchain installation for now...
      - run: cargo risczero install --version $RISC0_TOOLCHAIN_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RISC0_TOOLCHAIN_VERSION: v2024-04-22.0

      - name: build
        run: cargo test --release --no-run
        working-directory: website/doc-test/stable
      - name: test
        run: cargo test --release
        working-directory: website/doc-test/stable

      - run: sccache --show-stats
