[package]
name = "substrate-minimal-runtime"
version = "0.1.0"
description = "Minimal Substrate runtime for testing compatibility"
publish = false

[workspace]

[package.metadata.release]
release = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# this is a hack to workaround issues with "std" not being configured for borsh
borsh = { version = "1.5", default-features = false, features = ["std"] }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk/", tag = "polkadot-stable2407", default-features = false }
risc0-zkvm = { path = "../../risc0/zkvm", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk/", tag = "polkadot-stable2407", default-features = false, features = [
  "serde",
] }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/polkadot-sdk/", tag = "polkadot-stable2407", optional = true }

[features]
default = ["std"]
std = ["frame-support/std", "substrate-wasm-builder"]
