[package]
name = "keccak-methods"
version = "0.1.0"
edition = "2024"
publish = false

[build-dependencies]
risc0-build = { path = "../../../risc0/build" }

[package.metadata.risc0]
methods = ["guest"]
